import type { Metadata } from "next";
// import localFont from "next/font/local";
import { Poppins, DM_Mono, DM_Sans } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";
import { AppHeader } from "@/components/landing";


const FPoppins = Poppins({
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
})
const FDM_Mono = DM_Mono({
  display: "swap",
  weight: ["300", "400", "500"],
  variable: "--font-mono",
  subsets: ["latin"],
})
const FDM_Sans = DM_Sans({
  display: "swap",
  weight: ["300", "400", "500"],
  variable: "--font-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(FPoppins.className, FDM_Mono.variable, FDM_Sans.variable, "relative")}
      >
        <AppHeader/>
        {children}
      </body>
    </html>
  );
}
